[global_tags]
  user = "${USER}"

#------------------------
# INPUT CPU ET MEM
#------------------------
# Collecte des métriques CPU et mémoire
[[inputs.cpu]]
  # Indiquer les statistiques par processeur
  percpu = true
  # Indiquer les statistiques totales d'utilisation du processeur par système
  totalcpu = true
  # Collecter les métriques brutes de temps processeur
  collect_cpu_time = false
  ## si true, rapporte le temps actif du CPU
  ## NOTE: le resultat de cette métrique peut différer de la somme des autres métriques CPU
  report_active = false
  ## si true, n'ajoute pas les tags 'cpu' aux métriques CPU
  core_tags = false

[[inputs.mem]]
    # Par défaut

#------------------------
# OUTPUT INFLUXDB
#------------------------
[[outputs.influxdb_v2]]
  urls = ["http://${INFLUXDB_HOST}"]
  token = "${INFLUXDB_TOKEN}"
  organization = "${INFLUXDB_ORG}"
  bucket = "${INFLUXDB_BUCKET}"