name: Terraform Deploy to AWS

on:
  workflow_dispatch:
  push:
    inputs: # inputs sert à définir des paramètres lors du déclenchement manuel du workflow
      environment:
        description: 'Environment to deploy'
        required: false
        default: 'dev'
        type: choice
        options:
          - dev
          - staging
          - production

jobs:
  terraform-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      #  On crée le bucket S3
      - name: Check and Create Backend Infrastructure
        run: |
          if ! aws s3api head-bucket --bucket terraform-state-heh-workflow-terraform 2>/dev/null; then
            echo "Creating S3 bucket..."
            aws s3api create-bucket --bucket terraform-state-heh-workflow-terraform --region us-east-1
            aws s3api put-bucket-versioning --bucket terraform-state-heh-workflow-terraform --versioning-configuration Status=Enabled # Enable versioning
          else
            echo "S3 bucket already exists."
          fi

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -var="environment=${{ inputs.environment }}" -out=tfplan # sauvegarder le plan dans un fichier

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan # applique en utilisant le fichier de plan

      - name: Show Infrastructure Output
        run: terraform output
