- hosts: web_servers
  vars:
    server_name: "web"
    message: "Bienvenue au DST"
  tasks:
    - name: Install apache2
      package:
        name: apache2
        state: present
    - name: Start the apache2 server
      service:
        name: apache2
        state: started
    - name: Add the index.html file
      template:
        src: index.html.j2
        dest: /var/www/localhost/htdocs/index.html