# syntax=docker/dockerfile:1

# Define the base image
ARG PYTHON_VERSION=3.14.0a2
ARG ALPINE_RELEASE=3.21
FROM python:${PYTHON_VERSION}-alpine${ALPINE_RELEASE} AS base

# Install packages
RUN apk add --update --no-cache \
    openssh \
    nano \
    openrc \
    ansible \
    curl

# Configure init system
RUN openrc default

# Configure Ansible
RUN mkdir /etc/ansible \
    && ansible-config init --disabled > /etc/ansible/ansible.cfg \
    && sed -i 's|^;\s*interpreter_python\s*=\s*auto\s*|interpreter_python=auto_silent|' /etc/ansible/ansible.cfg

# Configure SSH
ADD id_rsa /root
RUN sed -i s/#PermitRootLogin.*/PermitRootLogin\ yes/ /etc/ssh/sshd_config \
    && echo "StrictHostKeyChecking no" >> /etc/ssh/ssh_config \
    && echo "LogLevel ERROR" >> /etc/ssh/ssh_config \
    && echo "root:root" | chpasswd \
    && cd /root && mkdir /root/.ssh/ \
    && cp /root/id_rsa /root/.ssh/ \
    && chmod 400 /root/.ssh/id_rsa \
    && chmod 400 /root/id_rsa
EXPOSE 22

# Define the working directory
WORKDIR /shared

# Define the entrypoint
COPY start.sh /start.sh
RUN chmod +xs /start.sh
ENTRYPOINT ["/start.sh"]